
name: CI Build

on:
  push:
    branches: [approxsmc,approxasp]
  pull_request:
    branches: [approxsmc,approxasp]

jobs:
  build:
    name: ${{ matrix.name }}
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5
        with:
          submodules: recursive

      - name: Install libraries
        run: sudo apt-get update && sudo apt-get install -y build-essential cmake bison re2c

      - name: Run build
        run: |
          mkdir build && cd build
          cmake -DCLINGO_BUILD_SHARED=ON ..
          make -j12
          
      - name: Check Binary
        run: |
          ls build/approxasp

      - name: Sample Run ApproxASP 1
        run: |
          cp build/approxasp .
          ./approxasp --useind IS_molise.lp --asp molise.lp 2>&1 | tee /tmp/out.txt
          grep -q "final ApproxASP estimate" /tmp/out.txt

      - name: Sample Run ApproxASP 2
        run: |
          cp build/approxasp .
          ./approxasp --asp vertex-cover.lp 2>&1 | tee /tmp/out.txt
          grep -q "final ApproxASP estimate" /tmp/out.txt
